"""剧本生成工作流服务。"""

from typing import Any

from src.domain.script_design import ScriptGenerationRequest, ScriptGenerationResult
from src.domain.source_context import SourceContext
from src.generation.iterative_agent_context_provider import IterativeAgentContextProvider
from src.generation.opensearch_agent_context_provider import OpenSearchAgentContextProvider
from src.generation.retrieval_planner import QwenRetrievalPlanner
from src.generation.script_generator import QwenScriptGenerator


class ScriptGenService:
    """编排 query 改写、资料检索和剧本初稿生成。"""

    def __init__(
        self,
        search_provider: OpenSearchAgentContextProvider | None = None,
        planner: QwenRetrievalPlanner | None = None,
        generator: QwenScriptGenerator | None = None,
    ) -> None:
        self._search_provider = search_provider or OpenSearchAgentContextProvider.from_env()
        self._planner = planner or QwenRetrievalPlanner()
        self._generator = generator or QwenScriptGenerator()

    @classmethod
    def from_env(cls) -> "ScriptGenService":
        """使用 .env 构建剧本生成服务。"""

        return cls()

    def generate_script(self, request: ScriptGenerationRequest) -> ScriptGenerationResult:
        rewritten_queries = self.resolve_queries(request)
        contexts = self._search_provider.find_contexts_for_queries(rewritten_queries)
        contexts = contexts[: request.max_contexts]
        script = self._generator.generate(request.query, contexts, request.feedback)
        return ScriptGenerationResult(
            script=script,
            contexts_used=contexts,
            rewritten_queries=rewritten_queries,
            generation_notes=[
                "Generated by script generation v0 pipeline.",
                "Output is a small structured draft, not a complete 90-day script.",
            ],
            original_query=request.query,
            feedback=request.feedback,
        )

    def revise_script(
        self,
        previous_result: dict[str, Any],
        query: str,
        feedback: str,
    ) -> ScriptGenerationResult:
        """复用旧稿资料，根据人工反馈生成下一轮修订稿。"""

        previous_script = previous_result.get("script")
        if not isinstance(previous_script, dict) or not previous_script:
            raise ValueError("旧稿 JSON 缺少有效的 script 字段")
        if not feedback.strip():
            raise ValueError("修订剧本时 feedback 不能为空")

        contexts = self._build_contexts(previous_result.get("contexts_used"))
        rewritten_queries = self._string_list(previous_result.get("rewritten_queries"))
        original_query = previous_result.get("original_query")
        if not isinstance(original_query, str) or not original_query.strip():
            original_query = query

        previous_round = previous_result.get("revision_round", 0)
        if not isinstance(previous_round, int) or isinstance(previous_round, bool):
            previous_round = 0

        script = self._generator.revise(
            original_query,
            previous_script,
            contexts,
            feedback,
        )
        return ScriptGenerationResult(
            script=script,
            contexts_used=contexts,
            rewritten_queries=rewritten_queries,
            generation_notes=[
                f"Revised from an existing draft using human feedback, round {previous_round + 1}.",
                "Reused the previous retrieval contexts without querying OpenSearch again.",
            ],
            original_query=original_query,
            feedback=feedback.strip(),
            revision_round=previous_round + 1,
        )

    def resolve_queries(self, request: ScriptGenerationRequest) -> list[str]:
        """解析或改写剧本检索 query，供 CLI 人工确认使用。"""

        manual_queries = [query.strip() for query in request.manual_queries if query.strip()]
        if manual_queries:
            return manual_queries[:3]

        rewritten_queries = self._planner.rewrite_initial_queries(request.query)
        if rewritten_queries:
            return rewritten_queries[:3]
        return [request.query.strip()]

    def _build_contexts(self, value: Any) -> list[SourceContext]:
        if not isinstance(value, list):
            return []

        contexts = []
        for item in value:
            if not isinstance(item, dict):
                continue
            context_id = item.get("id")
            title = item.get("title")
            content = item.get("content")
            metadata = item.get("metadata")
            if not all(isinstance(field, str) and field.strip() for field in (context_id, title, content)):
                continue
            contexts.append(
                SourceContext(
                    id=context_id,
                    title=title,
                    content=content,
                    metadata=metadata if isinstance(metadata, dict) else {},
                )
            )
        return contexts

    def _string_list(self, value: Any) -> list[str]:
        if not isinstance(value, list):
            return []
        return [item.strip() for item in value if isinstance(item, str) and item.strip()]
