"""剧本生成工作流服务。"""

from src.domain.script_design import ScriptGenerationRequest, ScriptGenerationResult
from src.domain.source_context import SourceContext
from src.generation.iterative_agent_context_provider import IterativeAgentContextProvider
from src.generation.opensearch_agent_context_provider import OpenSearchAgentContextProvider
from src.generation.retrieval_planner import QwenRetrievalPlanner
from src.generation.script_generator import QwenScriptGenerator


class ScriptGenService:
    """编排 query 改写、资料检索和剧本初稿生成。"""

    def __init__(
        self,
        search_provider: OpenSearchAgentContextProvider | None = None,
        planner: QwenRetrievalPlanner | None = None,
        generator: QwenScriptGenerator | None = None,
    ) -> None:
        self._search_provider = search_provider or OpenSearchAgentContextProvider.from_env()
        self._planner = planner or QwenRetrievalPlanner()
        self._generator = generator or QwenScriptGenerator()

    @classmethod
    def from_env(cls) -> "ScriptGenService":
        """使用 .env 构建剧本生成服务。"""

        return cls()

    def generate_script(self, request: ScriptGenerationRequest) -> ScriptGenerationResult:
        rewritten_queries = self._resolve_queries(request)
        contexts = self._search_provider.find_contexts_for_queries(rewritten_queries)
        contexts = contexts[: request.max_contexts]
        script = self._generator.generate(request.query, contexts)
        return ScriptGenerationResult(
            script=script,
            contexts_used=contexts,
            rewritten_queries=rewritten_queries,
            generation_notes=[
                "Generated by script generation v0 pipeline.",
                "Output is a small structured draft, not a complete 90-day script.",
            ],
        )

    def _resolve_queries(self, request: ScriptGenerationRequest) -> list[str]:
        manual_queries = [query.strip() for query in request.manual_queries if query.strip()]
        if manual_queries:
            return manual_queries[:3]

        rewritten_queries = self._planner.rewrite_initial_queries(request.query)
        if rewritten_queries:
            return rewritten_queries[:3]
        return [request.query.strip()]
