"""基于 Qwen 的 NPC Agent 生成器。"""

from hashlib import sha256
import json
from typing import Any

from src.config import QwenConfig
from src.domain.agent_generation import AgentGenerationRequest, AgentGenerationResult
from src.domain.npc_agent import NpcAgentConfig
from src.generation.npc_agent_generator import NpcAgentGenerator
from src.generation.qwen_client import ChatMessage, QwenChatClient


class QwenGenerationError(RuntimeError):
    """当 Qwen 输出无法转换为 NPC Agent 配置时抛出。"""


class QwenNpcAgentGenerator(NpcAgentGenerator):
    """通过 Qwen 生成结构化 NPC Agent 配置。"""

    def __init__(self, client: QwenChatClient | None = None) -> None:
        self._client = client or QwenChatClient(QwenConfig.from_env())

    def generate(self, request: AgentGenerationRequest) -> AgentGenerationResult:
        query = request.query.strip()
        if not query:
            raise ValueError("query must not be empty")

        content = self._client.complete(self._build_messages(request))
        payload = self._parse_json_object(content)
        agent = self._build_agent(query, request, payload)

        return AgentGenerationResult(
            agent=agent,
            contexts_used=list(request.contexts),
            generation_notes=["Generated by Qwen via DashScope OpenAI-compatible chat completions."],
        )

    def _build_messages(self, request: AgentGenerationRequest) -> list[ChatMessage]:
        contexts = [
            {
                "reference_id": context.id,
                "title": context.title,
                "content": context.content,
                "metadata": context.metadata,
                "citation_label": f"{context.id} - {context.title}",
            }
            for context in request.contexts
        ]
        user_payload = {
            "query": request.query,
            "source_contexts": contexts,
            "citation_requirements": {
                "format": "（参考：reference_id - title）",
                "fields_requiring_citations": [
                    "role",
                    "background",
                    "goals",
                    "personality_traits",
                    "knowledge_summary",
                    "dialogue_style",
                    "behavior_rules",
                ],
                "rules": [
                    "除 name 外，每个设定字段都必须在句末或条目末尾标注参考来源。",
                    "goals、personality_traits、behavior_rules 中的每一个列表项都必须各自标注参考来源。",
                    "只能引用 source_contexts 中真实存在的 reference_id 和 title，不要编造文档。",
                    "如果某项只来自原始 query 而非外部资料，使用（参考：原始需求）。",
                    "如果一个设定综合多个资料，可以标注多个参考，例如（参考：doc-1 - 标题A；doc-2 - 标题B）。",
                ],
            },
            "required_json_fields": [
                "name",
                "role",
                "background",
                "goals",
                "personality_traits",
                "knowledge_summary",
                "dialogue_style",
                "behavior_rules",
            ],
        }

        return [
            ChatMessage(
                role="system",
                content=(
                    "你为剧情向严肃游戏生成结构化 NPC Agent 配置。"
                    "必须只返回一个合法 JSON 对象，不要使用 Markdown 包裹。"
                    "如果用户 query 是中文，输出必须使用中文。"
                    "生成的设定必须可追溯：除 name 外，每个设定字段都要标注参考来源。"
                ),
            ),
            ChatMessage(role="user", content=json.dumps(user_payload, ensure_ascii=False)),
        ]

    def _parse_json_object(self, content: str) -> dict[str, Any]:
        cleaned = content.strip()
        if cleaned.startswith("```"):
            cleaned = cleaned.strip("`").strip()
            if cleaned.lower().startswith("json"):
                cleaned = cleaned[4:].strip()

        try:
            parsed = json.loads(cleaned)
        except json.JSONDecodeError as exc:
            raise QwenGenerationError("Qwen response was not valid JSON") from exc

        if not isinstance(parsed, dict):
            raise QwenGenerationError("Qwen response must be a JSON object")
        return parsed

    def _build_agent(
        self,
        query: str,
        request: AgentGenerationRequest,
        payload: dict[str, Any],
    ) -> NpcAgentConfig:
        source_context_ids = [context.id for context in request.contexts]
        return NpcAgentConfig(
            id=self._stable_agent_id(query),
            name=self._required_str(payload, "name"),
            role=self._required_str(payload, "role"),
            background=self._required_str(payload, "background"),
            goals=self._required_str_list(payload, "goals"),
            personality_traits=self._required_str_list(payload, "personality_traits"),
            knowledge_summary=self._required_str(payload, "knowledge_summary"),
            dialogue_style=self._required_str(payload, "dialogue_style"),
            behavior_rules=self._required_str_list(payload, "behavior_rules"),
            source_context_ids=source_context_ids,
        )

    def _stable_agent_id(self, query: str) -> str:
        digest = sha256(f"qwen:{query}".encode("utf-8")).hexdigest()[:12]
        return f"npc-agent-{digest}"

    def _required_str(self, payload: dict[str, Any], key: str) -> str:
        value = payload.get(key)
        if not isinstance(value, str) or not value.strip():
            raise QwenGenerationError(f"Qwen response field '{key}' must be a non-empty string")
        return value.strip()

    def _required_str_list(self, payload: dict[str, Any], key: str) -> list[str]:
        value = payload.get(key)
        if not isinstance(value, list):
            raise QwenGenerationError(f"Qwen response field '{key}' must be a list")

        items = [item.strip() for item in value if isinstance(item, str) and item.strip()]
        if not items:
            raise QwenGenerationError(f"Qwen response field '{key}' must contain strings")
        return items
